-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgGhxChQzxclQDCcwv
Z7P4ywKBOGwv/Sknbhmgcgc1ATygCgYIKoZIzj0DAQehRANCAARUk8adgBD7xCgj
gjqfVdEoVIjOLSzTKMr0loshIawE9nH18C3Is337i3myFBJ2qs49qYD+kg8dj2PB
Jc/PkNu5
-----END PRIVATE KEY-----